@EndpointsController_HostAddress = http://localhost:5217
@WalletName = Nowość
@WalletId = 681b47e5401d5e1c0c3af39b
@Code = MGA
@CodeTo = AFN

//Nowy portfel
POST {{EndpointsController_HostAddress}}/WalletCreate
Content-Type: application/json
{
  "name": "{{WalletName}}",
  "initValue": [
    {
      "code": "{{Code}}",
      "value": 10
    }
  ]
}

###


//Lista wszystkich portfeli
GET {{EndpointsController_HostAddress}}/WalletGet

###


//Konkretny portfel
GET {{EndpointsController_HostAddress}}/WalletGet?walletname={{WalletName}}

###


//Dodanie środków do portfela
POST {{EndpointsController_HostAddress}}/NewTransactionAdd
Content-Type: application/json
{
  "walletId": "{{WalletId}}",
  "code": "{{Code}}",
  "value": 50
}

###


//Wypłata środków z portfela
PUT {{EndpointsController_HostAddress}}/NewTransactionSubtract
Content-Type: application/json
{
  "walletId": "{{WalletId}}",
  "code": "{{Code}}",
  "value": 100
}


###

//Przewalutowanie środków
PUT {{EndpointsController_HostAddress}}/NewTransactionConvert
Content-Type: application/json
{
  "walletId": "{{WalletId}}",
  "codeFrom": "{{Code}}",
  "codeTo": "{{CodeTo}}",
  "value": 30
}

###
